# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/attica': 'Frameworks/6.24'
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/karchive': 'Frameworks/6.24'
    'frameworks/kauth': 'Frameworks/6.24'
    'frameworks/kcmutils': 'Frameworks/6.24'
    'frameworks/kcodecs': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kconfigwidgets': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kcrash': 'Frameworks/6.24'
    'frameworks/kdbusaddons': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kidletime': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'frameworks/knewstuff': 'Frameworks/6.24'
    'frameworks/knotifications': 'Frameworks/6.24'
    'frameworks/kservice': 'Frameworks/6.24'
    'frameworks/kitemmodels': 'Frameworks/6.24'
    'frameworks/kwidgetsaddons': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/kxmlgui': 'Frameworks/6.24'
    'frameworks/purpose': 'Frameworks/6.24'
    'frameworks/kstatusnotifieritem': 'Frameworks/6.24'
    'frameworks/kuserfeedback': 'Frameworks/6.24'
    'libraries/kirigami-addons': 'v1.11.0'
    'third-party/packagekit-qt': '@latest'
    'third-party/appstream': '@latest'

RuntimeDependencies:
 - 'on': ['Linux']
   'require':
    'sdk/selenium-webdriver-at-spi': '@same'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD']
 cmake-options: -DBUILD_RpmOstreeBackend=ON -DBUILD_SteamOSBackend=ON
