[Desktop Entry]
Name=Discover
Name[ar]=المستكشف
Name[ast]=Discover
Name[az]=Discover
Name[be]=Discover
Name[bg]=Discover
Name[ca]=Discover
Name[ca@valencia]=Discover
Name[cs]=Discover
Name[da]=Discover
Name[de]=Discover
Name[el]=Discover
Name[en_GB]=Discover
Name[eo]=Discover
Name[es]=Discover
Name[et]=Discover
Name[eu]=Discover
Name[fi]=Discover
Name[fr]=Discover
Name[gl]=Descubrir
Name[he]=Discover
Name[hi]=डिस्कवर
Name[hu]=Discover
Name[ia]=Discover (Discoperi)
Name[id]=Discover
Name[ie]=Discover
Name[is]=Discover
Name[it]=Discover
Name[ja]=Discover
Name[ka]=Discover
Name[ko]=Discover
Name[lt]=Discover
Name[lv]=Discover
Name[ml]=കണ്ടെത്തുക
Name[my]=ဒစ်(စ)ကာဗာ
Name[nb]=Discover
Name[nl]=Ontdekken
Name[nn]=Discover
Name[pa]=ਡਿਸਕਵਰ
Name[pl]=Odkrywca
Name[pt]=Discover
Name[pt_BR]=Discover
Name[ro]=Discover
Name[ru]=Discover
Name[sa]=डिस्कवर्
Name[sk]=Discover
Name[sl]=Discover
Name[sr]=Oткривач
Name[sr@ijekavian]=Oткривач
Name[sr@ijekavianlatin]=Otkrivač
Name[sr@latin]=Otkrivač
Name[sv]=Upptäck
Name[ta]=டிஸ்கவர்
Name[tg]=Кашфиёт
Name[tr]=Keşfet
Name[uk]=Discover
Name[x-test]=xxDiscoverxx
Name[zh_CN]=Discover 软件中心
Name[zh_TW]=Discover
MimeType=@DesktopMimeType@
Exec=@DesktopExec@
Icon=plasmadiscover
Type=Application
X-DocPath=plasma-discover/index.html
InitialPreference=5
NoDisplay=@DesktopNoDisplay@
Actions=Updates;
SingleMainWindow=true
GenericName=Software Center
GenericName[ar]=مركز البرمجيّات
GenericName[ast]=Centru de software
GenericName[az]=Proqram Təminatı Mərkəzi
GenericName[be]=Цэнтр праграмнага забеспячэння
GenericName[bg]=Софтуерен център
GenericName[ca]=Centre de programari
GenericName[ca@valencia]=Centre de programari
GenericName[cs]=Centrum softwaru
GenericName[da]=Softwarecenter
GenericName[de]=Programmverwaltung
GenericName[el]=Κέντρο λογισμικού
GenericName[en_GB]=Software Centre
GenericName[eo]=Programaro-Centro
GenericName[es]=Centro de software
GenericName[et]=Tarkvarakeskus
GenericName[eu]=Software gunea
GenericName[fi]=Sovellusvalikoima
GenericName[fr]=Logithèque
GenericName[gl]=Centro de Software
GenericName[he]=מרכז התוכנה
GenericName[hi]=सॉफ्टवेयर केन्द्र
GenericName[hsb]=Srjedźišćo za software
GenericName[hu]=Szoftverközpont
GenericName[ia]=Centro de Software
GenericName[id]=Pusat Perangkat Lunak
GenericName[ie]=Programmarium
GenericName[is]=Hugbúnaðarmiðstöð
GenericName[it]=Software Center
GenericName[ja]=ソフトウェアセンター
GenericName[ka]=პროგრამების ცენტრი
GenericName[ko]=소프트웨어 센터
GenericName[lt]=Programinės įrangos centras
GenericName[lv]=Programmatūras centrs
GenericName[ml]=സോഫ്റ്റ്വെയർ സെന്റർ
GenericName[my]=ဆော့ဖ်ဝဲလ်စင်တာ
GenericName[nb]=Programvaresenter
GenericName[nl]=Softwarecentrum
GenericName[nn]=Programvaresenter
GenericName[pa]=ਸਾਫਟਵੇਅਰ ਸੈਂਟਰ
GenericName[pl]=Ośrodek programów
GenericName[pt]=Centro de Aplicações
GenericName[pt_BR]=Central de aplicativos
GenericName[ro]=Centru de aplicații
GenericName[ru]=Центр программ
GenericName[sa]=तन्त्रांश् केन्द्र
GenericName[sk]=Centrum softvéru
GenericName[sl]=Programsko središče
GenericName[sr]=Софтверски центар
GenericName[sr@ijekavian]=Софтверски центар
GenericName[sr@ijekavianlatin]=Softverski centar
GenericName[sr@latin]=Softverski centar
GenericName[sv]=Programvarucentral
GenericName[ta]=மென்பொருள் மையம்
GenericName[tg]=Маркази нармафзор
GenericName[tr]=Yazılım Merkezi
GenericName[uk]=Центр програм
GenericName[x-test]=xxSoftware Centerxx
GenericName[zh_CN]=软件中心
GenericName[zh_TW]=軟體中心
Categories=Qt;KDE;System;
Keywords=program;software;store;repository;package;add;install;uninstall;remove;update;apps;applications;games;flatpak;snap;addons;add-ons;firmware;

[Desktop Action Updates]
Name=See Available Updates
Name[ar]=اعرض التحديثات المتوفرة
Name[az]=Əlçatan yenilənmələrə baxın
Name[be]=Паглядзець даступныя абнаўленні
Name[bg]=Преглед на наличие актуализации
Name[ca]=Mostra les actualitzacions disponibles
Name[ca@valencia]=Mostra les actualitzacions disponibles
Name[cs]=Zobrazit dostupné aktualizace
Name[de]=Zeigt verfügbare Aktualisierungen
Name[el]=Προβολή Διαθέσιμων Ενημερώσεων
Name[en_GB]=See Available Updates
Name[eo]=Rigardi Disponeblajn Ĝisdatigojn
Name[es]=Ver las actualizaciones disponibles
Name[eu]=Ikusi eguneratze erabilgarriak
Name[fi]=Näytä saatavilla olevat päivitykset
Name[fr]=Consulter les mises à jour disponibles
Name[gl]=Ver as actualizacións dispoñíbeis
Name[he]=הצגת עדכונים זמינים
Name[hi]=उपलब्ध अद्यतन देखें
Name[hsb]=Pokaž móžne aktualizowanja
Name[hu]=Elérhető frissítések megtekintése
Name[ia]=Vide actualisationes dispoibile
Name[id]=Lihat Pembaruan Tersedia
Name[ie]=Vider li disponibil actualisamentes
Name[is]=Sjá uppfærslur í boði
Name[it]=Vedi gli aggiornamenti disponibili
Name[ja]=利用可能な更新を見る
Name[ka]=ხელმისაწვდომი განახლებების ნახვა
Name[ko]=사용 가능한 업데이트 보기
Name[lt]=Rodyti prieinamus atnaujinimus
Name[lv]=Skatīt pieejamos atjauninājumus
Name[ml]=ലഭ്യമായ അപ്ഡേറ്റുകൾ കാണുക
Name[my]=ရရှိနိုင်သော အပ်ဒိတ်များ ကြည့်မည်
Name[nb]=Se tilgjengelige oppdateringer
Name[nl]=Zie beschikbare updates
Name[nn]=Sjå tilgjengelege oppdateringar
Name[pa]=ਮੌਜੂਦ ਅੱਪਡੇਟ ਵੇਖੋ
Name[pl]=Obejrzyj dostępne uaktualnienia
Name[pt]=Ver as Actualizações Disponíveis
Name[pt_BR]=Ver as atualizações disponíveis
Name[ro]=Vezi actualizările disponibile
Name[ru]=Просмотреть доступные обновления
Name[sa]=उपलब्धानि अद्यतनानि पश्यन्तु
Name[sk]=Zobraziť dostupné aktualizácie
Name[sl]=Poglej razpoložljive posodobitve
Name[sv]=Se Tillgängliga uppdateringar
Name[ta]=கிடைக்கும் புதுப்பிப்புகளை காட்டும்
Name[tr]=Kullanılabilir Güncellemeleri Gör
Name[uk]=Перегляд доступних оновлень
Name[x-test]=xxSee Available Updatesxx
Name[zh_CN]=查看可用更新
Name[zh_TW]=檢視可用的更新
Icon=update-low
Exec=plasma-discover --mode update
