#!/usr/bin/env python
# -*- coding: utf-8 -*-

# releasechecker.py
#
#  Copyright (c) 2010 Jonathan Thomas <echidnaman@kubuntu.org>
#
#  Author: Jonathan Thomas <echidnaman@kubuntu.org>
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as
#  published by the Free Software Foundation; either version 2 of
#  the License or (at your option) version 3 or any later version
#  accepted by the membership of KDE e.V. (or its successor approved
#  by the membership of KDE e.V.), which shall act as a proxy
#  defined in Section 14 of version 3 of the license.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys, time
sys.path.insert(0, '/usr/lib/update-notifier')

from UpdateManager.Core.MetaRelease import MetaReleaseCore

if __name__ == "__main__":
    """ check for updates, if there are any say so """
    #FIXME: implement command line options for MetaReleaseCore args
    metaRelease = MetaReleaseCore(False, False)
    while metaRelease.downloading:
        time.sleep(1)
    new_dist = metaRelease.new_dist

    if new_dist is not None:
        print("we haz an release")
        sys.exit(0)
    else:
        print("No new release at this moment")
        sys.exit(1)

